### PR TITLE
Update autounattend.xml

### PR DESCRIPTION
**Pull request by Basmart**

### CODE REVIEW

**Comment by Basmart** [comment]
It works regardles ExecutionPolicy being restricted

**Comment by Querzion** [comment]
Is it difficult to make a file after using it and put the file there manually. it's on the desktop for a reason. It's the first thing  you see after you have installed the os. "/

**Comment by Basmart** [comment]
Hello, i have created different method of launching ps1 file from cmd command bypassing ExecutionPolicy.
Also ps1 file created with utf8 contains BOM so regardless how hard you try script won't work.

Also im last update i made cmd file to be placed on Public Desktop so it is visable as Firs Thing on Desktop


Kind regards,

Marcin.

**Comment by ViwuAndYouKnow** [comment]
I have fixed it. will create a new pull request.

**Comment by Basmart** [comment]
I am bit silly on Github not uderstanding Forks, pulls etc, is there any YT video explaining all of this?
my brain is tuned for SharePoint collaboration

:-)

**Comment by memstechtips** [comment]
Thanks all but I fixed it in https://github.com/memstechtips/UnattendedWinstall/commit/a9348a19ad425bb840c2a3e4e67501a81715ef66

**Pull request closed without merging**
